# Generated by Django 5.2 on 2025-05-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='image',
        ),
        migrations.AddField(
            model_name='graph',
            name='graph_image',
            field=models.ImageField(blank=True, upload_to='graphs/'),
        ),
    ]
