# Generated by Django 5.2 on 2025-05-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('registered', 'Registered'), ('guest', 'Guest')], default='registered', max_length=20),
        ),
    ]
