# Generated by Django 5.2.1 on 2025-05-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='a',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='b',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='c',
        ),
        migrations.AddField(
            model_name='graph',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
